---
backend:
  branch: main
  name: git-gateway
collections:
  - create: true
    fields:
      - default: post
        label: Layout
        name: layout
        widget: hidden
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Author
        name: author
        widget: string
      - label: Catergories
        name: catergories
        widget: list
      - label: Content
        name: content
        widget: markdown
    folder: src/_posts/
    label: Blog
    name: blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
media_folder: src/images/posts
