backend:
  name: git-gateway
  branch: main
media_folder: "images/posts"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - label: "Catergories"
        name: "catergories"
        widget: "list"
      - { label: "Content", name: "content", widget: "markdown" }
